### ISSUE TITLE
default %ziggurat fungible/nft tests do not pass

### ISSUE THREAD

**Issue by 0x70b1a5** [uqbar-dao/uqbar-core#243]
|nonf|fun|
|-|-
![image](https://user-images.githubusercontent.com/10970247/199097615-a3859a97-f959-4f1f-9f29-c7a5409aad8b.png) | ![image](https://user-images.githubusercontent.com/10970247/199097687-6befa30e-e0ae-4b02-a258-10f81fec16dd.png)

**Comment by dr-frmr** [comment]
This won't go away until the ziggurat frontend is realigned to the backend changes made here: https://github.com/uqbar-dao/uqbar-core/pull/207
