### ISSUE TITLE
ziggurat: test-surs should be built automatically

### ISSUE THREAD

**Issue by tadad** [uqbar-dao/uqbar-core#307]
`+$  test-surs` makes the user specify what sur files to look in for a particular type when molding test results. This works similarly to `/-` but we can also build all of this automatically - we can assume that the mold they want lives somewhere in the `/sur` directory for their project. When there is a change in `/sur`, start from zuse and build up all of their surs to get all the possible types they might want. This introduces some performance overhead, but I can't imagine it is that bad, and makes life easier for users

**Comment by tadad** [comment]
@hosted-fornet can we close this?

**Comment by hosted-fornet** [comment]
Yes
