### ISSUE TITLE
ziggurat: `%poke` -> `%dojo` fallback does not handle `sur`/`lib` imports

### ISSUE THREAD

**Issue by hosted-fornet** [uqbar-dao/uqbar-core#351]
`test-step` `%poke` -> `%dojo` fallback does not work for all cases. For example, if the `%poke` payload uses imported `sur`/`lib` files, it will not work, since those have not been imported for the `%dojo`-ifiied `%poke`. This should be possible, but will require some more orchestration. Specifically, something like:

1. Somehow fetch the `sur`/`lib` import file paths,
2. `-build-file` to faces in the `%dojo` before the `%dojo`-ified `%poke`.

**Comment by tadad** [comment]
there should be some way to do this without a mark. The code is buried somewhere deep in `/app/dojo/hoon` for when you have a "fake mark" in your `+on-poke`.

Though getting rid of fake marks all together and having people use `%noun` as the mark is not a bad pattern that people will use to get around that.

**Comment by hosted-fornet** [comment]
> there should be some way to do this without a mark. The code is buried somewhere deep in /app/dojo/hoon for when you have a "fake mark" in your +on-poke.

Hmm, good point, I didn't think to dig for this one.

> Though getting rid of fake marks all together and having people use %noun as the mark is not a bad pattern that people will use to get around that.

Maybe -- I'd prefer to not constrain devs who use %ziggurat to specific patterns for their apps, if we can avoid it. But if this is the only way, then it would be a reasonable solution.

**Comment by hosted-fornet** [comment]
closed in favor of https://github.com/uqbar-dao/dev-suite/issues/34 since we have moved repos
