### ISSUE TITLE
`payload:poke-payload` should be a `*` not a `@t`

### ISSUE THREAD

**Issue by tadad** [uqbar-dao/uqbar-core#370]
Poke payload in `sur/zig/ziggurat/hoon` is defined as:
`+$  poke-payload  [who=@p to=@p app=@tas mark=@tas payload=@t]`
but `payload` should actually be a `*` not a `@t`

**Comment by tadad** [comment]
@hosted-fornet can we close this?

**Comment by hosted-fornet** [comment]
Yes
