### ISSUE TITLE
"Whitelist" link not working

### ISSUE THREAD

**Issue by mjohngreene** [uqbar-dao/uqbar-core#438]
Hello.  I was looking to install this and kick the tires a little.  

Before proceeding, though, I am looking for the "whitelist" that is referenced a couple times in the README.  The links provided point to a rollup.hoon that does not appear to exist anymore.

**Comment by dr-frmr** [comment]
https://github.com/uqbar-dao/uqbar-core/blob/3d0514e366435553abbe4fecde7e28e43f77a45d/lib/zig/rollup.hoon#L11-L17

This is what you're looking for. Thanks for the heads up, I'll edit the README

**Comment by dr-frmr** [comment]
Fixed in #437
