### ISSUE TITLE
Core 0.1.4: completed transactions not showing in wallet FE

### ISSUE THREAD

**Issue by dr-frmr** [uqbar-dao/uqbar-core#443]
Steps to reproduce:
- boot new fakeship
- initialize local chain
- run a few transactions
- check history tab in wallet FE

I've verified that the JSON is coming through -- probably some misalignment in what's expected.

**Comment by willbach** [comment]
glob with fix: https://ziggurat-app-distro.s3.us-east-2.amazonaws.com/glob-0v4.gsjdk.u2bqk.k285d.e7gef.9mclj.glob

**Comment by dr-frmr** [comment]
excellent, working now!
