### ISSUE TITLE
Expected results of running tests

### ISSUE THREAD

**Issue by mjohngreene** [uqbar-dao/uqbar-core#448]
After installing per https://github.com/uqbar-dao/uqbar-core#initial-installation, the tests in the last step resulted in 
```
> -test ~[/=zig=/tests]
ok=%.n
~nec:dojo> 
```
Note that I was a little unclear as to which directory I should use to run the fakeship as I already had the Urbit binary installed (ie, I ran ```~/.urbit -F nec``` instead of ```~/mydir/urbit/pkg/.urbit -F nec```).  I do not suspect that was the reason the tests appear to have failed but am sharing anyway in case that info is useful/pertinent.

Please let me know what results I should expect from running the tests and/or whether it is critical to resolve the apparent failure before proceeding through the README.

**Comment by dr-frmr** [comment]
A lot of our tests are out of date. That command runs ALL the tests in the /tests folder, but what you want to do is run individual files, i.e.,

`-test /=zig=/tests/lib/engine/hoon ~`

The main tests that I know are up-to-date now are lib/engine.hoon and contracts/zigs.hoon.
